version: 2
updates:
  # Maintain dependencies for GitHub actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    reviewers:
      - AplinkosMinisterija/biip-devops
