# Commenting part is based on https://github.com/cloudflare/pages-action/issues/16
name: Cloudflare Pages publish
description: Publish to Cloudflare Pages

inputs:
  cloudflare-api-token:
    description: Cloudflare API Token
    required: true
  cloudflare-account-id:
    description: Cloudflare Account ID
    required: true
  cloudflare-project-name:
    description: The name of the Pages project to upload to
    required: true
  artifact-name:
    description: Name of the artifact to download
    required: true

runs:
  using: composite
  steps:
    - name: Download distribution artefact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artefact-name }}
        path: cloudflare-pages-distribution

    - run: ls -lah cloudflare-pages-distribution
      shell: bash

    - name: Publish to Cloudflare Pages
      uses: cloudflare/pages-action@v1
      id: cloudflare
      with:
        apiToken: ${{ inputs.cloudflare-api-token }}
        accountId: ${{ inputs.cloudflare-account-id }}
        projectName: ${{ inputs.cloudflare-project-name }}
        directory: cloudflare-pages-distribution
        gitHubToken: ${{ github.token }}
        wranglerVersion: '3'
