name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  checkov-scan:
    runs-on: ubuntu-latest
    name: Checkov checks
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Checkov check
        uses: bridgecrewio/checkov-action@v12
        with:
          # This will add both a CLI output to the console and create a results.sarif file
          output_format: cli,sarif
          output_file_path: console,results.sarif
          quiet: true # optional: display only failed checks
          skip_check: CKV_DOCKER_2,CKV_DOCKER_3,CKV2_GHA_1

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2

        # Results are generated only on a success or failure
        # this is required since GitHub by default won't run the next step
        # when the previous one has failed. Security checks that do not pass will 'fail'.
        # An alternative is to add `continue-on-error: true` to the previous step
        # Or 'soft_fail: true' to checkov.
        if: success() || failure()
        with:
          sarif_file: results.sarif

  test-docker-build-push:
    name: Test docker build/push reusable workflow
    uses: ./.github/workflows/docker-build-push.yml
    permissions:
      contents: read
      packages: write
    with:
      docker-image: ghcr.io/aplinkosministerija/example
      docker-context: test
      environment: test
      runs-on: ubuntu-latest
      latest-tag: true
      push: false

  test-docker-build-tag-push-action:
    name: Test docker build tag push action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build & tag docker image
        uses: ./.github/actions/docker-build-tag-push
        with:
          docker-context: test
          environment: test
          push: false

  actionlint:
    name: Lint GitHub Actions workflows
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3

      - name: Check workflow files
        uses: docker://rhysd/actionlint:latest
        with:
          args: -color
